### PR TITLE
Remove Aqueel from the user mappings

### PR DESCRIPTION
**Pull request by lollkebear**
Aqueel doesn't work with us anymore but still gets added as a  reviewer https://github.com/cookpad/global-web/pull/27370

### CODE REVIEW

**Comment by rikarumi** [comment]
@lollkebear while at this, do you mind to also include removing him from the buddy map as well? 🙏🏼 
https://github.com/cookpad/cp8/blob/83b73513ced2ad8165b0129237e820b05637819f/lib/buddy_mappings.yml#L13-L14

**Comment by sikachu** [comment]
> but still gets added as a reviewer

I think this is due to him still in the [web-chapter](https://github.com/orgs/cookpad/teams/web-chapter/members). Shouldn't matter if he's in the mapping or not.

@dannyd4315 since you're the one marked as "maintainer", would you mind removing him from the team? (and maybe promoting @robertomiranda as another maintainer?)

**Review by tejanium — APPROVED** [review]
Yes, this is mapping github account with slack account. Aqeel still included in PR reviewer rotation because he's still a member in `web-chapter` team, also technically he's still with us but on leave. The automatic offboarding will kick in and remove him from `web-chapter` team. But I don't think that automatic offboarding will remove him from user mapping, so yes this is necessary as well.

**Comment by rikarumi** [comment]
thank you @lollkebear!

**Pull request merged**
