### PR TITLE
Show PR title in ReviewCompleteNotification slack messages

### PR DESCRIPTION
**Pull request by mshka**
what do you think about showing PR title in review complete notifications

## Before:
Screenshot 2020-07-09 at 16 18 05

## Suggestion:
Screenshot 2020-07-09 at 16 18 33

### CODE REVIEW

**Comment by mshka** [comment]
@balvig, please 👀

**Comment by balvig** [comment]
I'm not opposed, but would like to better understand the use case if possible 🙇 

I remember deliberately trying to keep noise low overall, and leaving out the title for review responses, as it didn't feel necessary to our workflow?

**Comment by andrassy** [comment]
Just wondering if we might be able to bring this back to life? Seems close to what we were looking for in Search.

We now use cp-8 extensively across multiple repos in [#search-engineering-reviews](https://ckpd.slack.com/archives/CUG603X7Z) and the team has grown to 12+ now, so there are often many review work streams ongoing at once. This makes it hard, at a glance, to work out which PRs have had comments and approvals you might and might not be interested in. 

Maybe an even better solution would be for the subsequent messages to be threaded below the original post (maybe even using emojis at the root as well to indicate approval ✅ and comment 💬 ?). But I'm guessing that would be a much bigger change?

Would it be better if the "long responses" were made optional via config so teams can opt in to them on a per-repo basis?

**Comment by balvig** [comment]
Thank you @andrassy!

> Would it be better if the "long responses" were made optional via config so teams can opt in to them on a per-repo basis?

Ah, I was just looking for some context, as I wanted to understand the need for the feature before committing.
As it's not something I've personally felt as a problem (even with 20ish people), was having to rely on the submitter. 😅 

A look at ` #search-engineering-reviews` gives a good idea of the problem you're trying to solve 👍 and I think we could try this out first to see if it makes things noisy enough that we want to make it optional.

**Review by balvig — APPROVED** [review]
@mshka looks like there is a conflict to resolved, but otherwise 👍

**Comment by mshka** [comment]
@balvig resolved the conflict, can you please merge this, I do not have write access to this repo

**Pull request merged**
