### PR TITLE
Don't send notifications for draft PRs

### PR DESCRIPTION
**Pull request by balvig**
Disabling notifications for PRs in draft mode.
https://github.blog/2019-02-14-introducing-draft-pull-requests/

Next step will be notifying _coming out_ of draft mode.

### CODE REVIEW

**Comment by ChrisBr** [comment]
I really much like this 👍 

From the GitHub API docs:

> Note: The Draft Pull Request API is currently available for developers to preview. You can use this API to create a draft pull request or see whether a pull request is in draft state. See the blog post preview for more details. To access the new draft parameter during the preview period, you must provide a custom media type in the Accept header:
`application/vnd.github.shadow-cat-preview`

So I guess we need to set the header somewhere? Or do you want to wait until it is not in beta anymore?

**Comment by balvig** [comment]
@ChrisBr ah, I've kinda confirmed that this works, since I was able to make [this a draft PR_](https://github.com/cookpad/cp8/pull/78#event-2186086141) _but_...I currently have two problems:

1. For some reason I can't create draft PRs on `global-web`?? (even manually), the option is simply missing:

Screen Shot 2019-03-28 at 9 53 08

(Do you have any idea why? 🤔)

2. It seemed like GitHub actually didn't seen a webhook notification when bringing the PR out of draft 😭 which is when we would like actually to send the notification...I'm sure that's in the pipeline though, so maybe just need to test again every now and then.

As far as this PR goes, I think we can merge it, but I guess we won't have much use of it until we figure out those two things! 😓

**Comment by ChrisBr** [comment]
Screen Shot 2019-04-09 at 16 50 28

@balvig I just checked, I can create draft PRs in this repo, can you check again. If you can still not create draft PRs it might because you're maintainer/owner of the repo?

**Comment by balvig** [comment]
@ChrisBr ah sorry, to clarify: On _this_ repo I can create drafts (maybe because it's a public?), but not on any of our private repos 😢

**Comment by ChrisBr** [comment]
@balvig ah got it, confirming, can not create PR in global-web either.

> Draft pull requests are available in public repositories with GitHub Free and GitHub Pro, and in public and private repositories with GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server. If you are not seeing this feature, it is probably because the repository that you're working in does not meet that criteria. If you believe that your repository does meet these criteria and you're still not seeing the feature, please contact GitHub Support directly so that we can investigate.

https://github.community/t5/How-to-use-Git-and-GitHub/Draft-Pull-Requests-not-available/td-p/19139

Do we meet one of the criteria?

**Comment by tapster** [comment]
our plan is 'GitHub Platinum' which doesn't meet the criteria that they lay out above.

**Comment by ChrisBr** [comment]
> our plan is 'GitHub Platinum' which doesn't meet the criteria that they lay out above.

😢😢 
It seems like they want to promote to switch from legacy plan with this approach ...

**Comment by balvig** [comment]
(Going to go ahead and merge this for now either way).

**Pull request merged**
